title: Rajib Mitra
description: Software Engineer | Tech Enthusiast | Blogger
theme: jekyll-theme-hacker

# Social links 
github_username: rajibmitra
twitter_username: xDevLo
linkedin_username: mitrarajib

# Blog settings
show_downloads: false
google_analytics: # Add your GA ID if you want analytics
